# Generated by Django 4.1.7 on 2023-03-19 19:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('seniority', models.IntegerField()),
                ('shift', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=10)),
                ('table', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 3, 19, 21, 20, 42, 459966))),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(max_length=50)),
                ('sauce', models.CharField(default=None, max_length=50)),
                ('price', models.FloatField()),
                ('weight', models.IntegerField()),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeriaApp.chef')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiter', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeriaApp.order')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeriaApp.pizza')),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='orders',
            field=models.ManyToManyField(through='pizzeriaApp.PizzaOrder', to='pizzeriaApp.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(through='pizzeriaApp.PizzaOrder', to='pizzeriaApp.pizza'),
        ),
    ]
