# Generated by Django 4.1.7 on 2023-03-19 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeriaApp', '0002_alter_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaorder',
            name='instructions',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 21, 21, 32, 809746)),
        ),
    ]
