# Generated by Django 4.1.7 on 2023-03-20 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeriaApp', '0003_pizzaorder_instructions_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 8, 37, 3, 80770)),
        ),
    ]
