# Generated by Django 4.1.7 on 2023-03-27 09:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeriaApp', '0006_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 27, 12, 39, 9, 558065)),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='pizzeriaApp.chef'),
        ),
    ]
