# Generated by Django 4.1.7 on 2023-03-27 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeriaApp', '0007_alter_order_time_alter_pizza_chef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 27, 12, 54, 0, 625701)),
        ),
    ]
