# Generated by Django 4.1.7 on 2023-05-06 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizzeriaApp", "0009_alter_order_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="pizza",
            name="calories",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 6, 22, 35, 3, 916929)
            ),
        ),
    ]
